### ISSUE TITLE
POST - api/v1/oauth2/token

### ISSUE THREAD

**Issue by itsgitz** [IDN-Media/docs.partner-api.ice.id#3]
https://docs.partner-api.ice.id/swagger

**Comment by itsgitz** [comment]
Done https://github.com/IDN-Media/docs.partner-api.ice.id/commit/ad0ad6b1859f08d6103e16c7ad3cf949f9e7d326

**Comment by dannurdiana7** [comment]
Done ✅ 

Tester : Dinda



![Image](https://user-images.githubusercontent.com/119470438/220559897-9279d887-6b95-4753-a3ec-5563a222a740.png)
